#!/usr/bin/env node
/**
 * Assemble a deployable bundle in deploy/ (ROADMAP §0.7):  npm run package
 *   deploy/Dockerfile, deploy/app/…  hub source (no node_modules / .next / local data)
 *   deploy/games/ready/<id>/…        ONLY what players need per game: game.json, the entry folder, art/
 * Games come from ~/game/ready (symlinks are followed). Nothing outside a game's entry folder + art/ is ever copied,
 * so project roots, .git, source, tools and backups cannot leak into production.
 */
import fs from "node:fs";
import path from "node:path";

const hub = process.cwd(), root = path.resolve(hub, process.env.GAMES_ROOT ?? ".."), out = path.join(hub, "deploy");
// deploy/ is also the git repo that Coolify builds from: wipe everything except .git so history survives each release
fs.mkdirSync(out, { recursive: true });
for (const e of fs.readdirSync(out)) if (e !== ".git") fs.rmSync(path.join(out, e), { recursive: true, force: true });
fs.mkdirSync(path.join(out, "app"), { recursive: true });

// planning notes and agent files stay local; the repo is public and only needs what builds the image
const skip = new Set(["node_modules", ".next", "data", "deploy", "docs", "legacy", "tools", ".git", ".env.local", "tsconfig.tsbuildinfo", "ROADMAP.md", "DEPLOY.md", "AGENTS.md", "CLAUDE.md", ".DS_Store"]);
for (const e of fs.readdirSync(hub)) {
  if (skip.has(e) || e.startsWith(".next")) continue;
  fs.cpSync(path.join(hub, e), path.join(out, "app", e), { recursive: true, dereference: true });
}
for (const f of ["Dockerfile", "docker-compose.yaml"]) fs.copyFileSync(path.join(hub, "scripts", f), path.join(out, f));
fs.writeFileSync(path.join(out, ".gitignore"), ".DS_Store\n");
fs.writeFileSync(path.join(out, "README.md"), "# game-hub (deploy bundle)\n\nGenerated by `npm run package` in the game-hub project — do not edit here. Coolify builds this repo with docker-compose (`docker-compose.yaml`).\n");

const ready = path.join(root, "ready");
const ids = fs.existsSync(ready) ? fs.readdirSync(ready).filter((n) => !n.startsWith(".") && fs.existsSync(path.join(ready, n, "game.json"))) : [];
const cfg = JSON.parse(fs.readFileSync(path.join(hub, "hub.config.json"), "utf8"));
cfg.only = ids; // production shows exactly what is in ready/
fs.writeFileSync(path.join(out, "app", "hub.config.json"), JSON.stringify(cfg, null, 2) + "\n");
let total = 0;
for (const id of ids) {
  const src = path.join(ready, id), dst = path.join(out, "games", "ready", id);
  const m = JSON.parse(fs.readFileSync(path.join(src, "game.json"), "utf8"));
  const entryDir = path.dirname(m.entry);
  if (entryDir === "." || entryDir === "") throw new Error(`${id}: entry is in the project root — build to a dist folder first (see check-games)`);
  fs.mkdirSync(dst, { recursive: true });
  fs.cpSync(path.join(src, "game.json"), path.join(dst, "game.json"));
  fs.cpSync(path.join(src, entryDir), path.join(dst, entryDir), { recursive: true, dereference: true, filter: (f) => !path.basename(f).startsWith(".") || f === path.join(src, entryDir) || path.basename(f) === ".hub-dist" });
  // only the files game.json declares (key art, trailer): art/ and media/ folders often hold large working files too
  for (const rel of [...Object.values(m.art ?? {}), ...Object.values(m.media ?? {})].filter((v) => typeof v === "string")) {
    const f = path.join(src, rel);
    if (rel.includes("..") || !fs.existsSync(f)) continue;
    fs.mkdirSync(path.dirname(path.join(dst, rel)), { recursive: true });
    fs.copyFileSync(fs.realpathSync(f), path.join(dst, rel));
  }
  const size = (function sz(p) { const s = fs.statSync(p); return s.isDirectory() ? fs.readdirSync(p).reduce((a, n) => a + sz(path.join(p, n)), 0) : s.size; })(dst);
  total += size; console.log(`  ✓ ${id}  ${(size / 1048576).toFixed(1)} MB`);
}
if (!ids.length) throw new Error("no games in ready/ — nothing to package");
console.log(`\ndeploy/ ready: hub + ${ids.length} game(s), ${(total / 1048576).toFixed(1)} MB of game files.\n  docker build -t game-hub deploy/   (see DEPLOY.md)`);
